export const tags = [
  "webdev",
  "app",
  "writing",
  "ui/ux",
  "web page",
  "programming",
  "frontend",
  "backend",
  "full-stack",
  "mobile",
  "design",
  "responsive",
  "SEO",
  "ecommerce",
  "JavaScript",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Python",
  "Ruby on Rails",
  "PHP",
  "Java",
  "C#",
  "Swift",
  "Flutter",
  "Firebase",
  "WordPress",
  "Shopify",
  "Magento",
  "WooCommerce",
  "Bootstrap",
  "Material UI",
  "RESTful APIs",
  "GraphQL",
  "Version Control",
  "Git",
  "Agile Development",
  "User Experience",
  "User Interface",
  "Wireframing",
  "Prototyping",
  "Testing",
  "Debugging",
  "Performance Optimization",
  "Cross-Browser Compatibility",
  "Accessibility",
  "Responsive Images",
  "Progressive Web Apps",
  "Serverless",
  "Cloud Computing",
  "Data Visualization",
  "Database Management",
  "UI Animation",
  "Chatbots",
  "AI Integration",
  "Machine Learning",
  "AR/VR",
  "Blockchain",
  "Cryptocurrency",
  "Data Security",
  "Web Hosting",
  "Content Management",
  "Social Media Integration",
  "Payment Gateways",
  "Digital Marketing",
  "Search Engine Optimization",
  "Data Analytics",
  "User Testing",
  "User Surveys",
  "A/B Testing",
  "Conversion Rate Optimization",
  "Gamification",
  "Microinteractions",
  "SaaS",
  "PWA",
  "CMS",
  "UX Writing",
  "API Documentation",
  "Responsive Typography",
  "Dark Mode Design",
  "Web Accessibility",
  "Authentication",
  "Authorization",
  "Push Notifications",
  "Single Page Applications",
  "Data Visualization",
  "Infographics",
  "Cross-Platform Development",
  "Localization",
  "Internationalization",
  "Progressive Enhancement",
  "Web Security",
  "Blockchain Integration",
  "Data Privacy",
  "Web Analytics",
];
