export const tags = [
  "webdev",
  "app",
  "writing",
  "ui/ux",
  "web page",
  "programming",
  "frontend",
  "backend",
  "mobile",
  "design",
  "ecommerce",
  "SEO",
  "responsive",
  "database",
  "JavaScript",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Python",
  "Ruby on Rails",
  "PHP",
  "WordPress",
  "iOS",
  "Android",
  "Swift",
  "Java",
  "Flutter",
  "API",
  "testing",
  "user interface",
  "user experience",
  "graphic design",
  "content writing",
  "cybersecurity",
  "cloud computing",
  "data analytics",
  "machine learning",
  "artificial intelligence",
  "blockchain",
];
